import { useMemo } from "react";
import {
  AlertCircleIcon,
  DownloadIcon,
  FileTextIcon,
  ReportIcon,
  SortIcon,
  SuppliersIcon,
  SwapIcon,
} from "../../components/icons/Icons";
import { recentReports, reportCards } from "../../data/reports";
import "./Reports.css";

const cardIconMap = {
  summary: FileTextIcon,
  lowStock: AlertCircleIcon,
  movement: SwapIcon,
  valuation: ReportIcon,
  supplier: SuppliersIcon,
};

const getStatusClass = (status) =>
  `status-pill ${String(status || "").toLowerCase().replace(/\s+/g, "-")}`;

const Reports = () => {
  const cards = useMemo(() => reportCards, []);
  const reports = useMemo(() => recentReports, []);

  return (
    <section className="reports-page">
      <header className="reports-header">
        <div>
          <div className="breadcrumb">System / Reports</div>
          <h2>Analytics &amp; Reports</h2>
        </div>
        <button type="button" className="primary-button">
          <DownloadIcon className="button-icon" />
          Export All Data
        </button>
      </header>

      <div className="reports-cards">
        {cards.map((card) => {
          const Icon = cardIconMap[card.icon];
          return (
            <article className="report-card" key={card.id}>
              <div className={`report-icon ${card.tone}`}>
                {Icon ? <Icon /> : null}
              </div>
              <h3>{card.title}</h3>
              <p>{card.description}</p>
              <div className="report-actions">
                <button type="button" className="ghost-button">
                  Generate
                </button>
                <button type="button" className="ghost-button">
                  Export
                </button>
              </div>
            </article>
          );
        })}
      </div>

      <div className="reports-table-card mobile-card-table">
        <div className="reports-table-header">
          <h3>Recent Reports</h3>
          <div className="reports-table-actions">
            <button type="button" className="icon-button" aria-label="Filter">
              <SortIcon />
            </button>
            <button type="button" className="icon-button" aria-label="Refresh">
              <SwapIcon />
            </button>
          </div>
        </div>

        <div className="table-header">
          <span>Report Name</span>
          <span>Date Created</span>
          <span>Generated By</span>
          <span>Status</span>
          <span>Downloads</span>
        </div>
        <div className="table-body">
          {reports.map((report) => (
            <div className="table-row" key={report.id}>
              <div className="cell report-name full" data-label="Report Name">
                <span className="file-icon">
                  <FileTextIcon />
                </span>
                <strong>{report.name}</strong>
              </div>
              <div className="cell muted" data-label="Date Created">
                {report.created}
              </div>
              <div className="cell muted" data-label="Generated By">
                {report.generatedBy}
              </div>
              <div className="cell" data-label="Status">
                <span className={getStatusClass(report.status)}>
                  {report.status}
                </span>
              </div>
              <div className="cell downloads-cell" data-label="Downloads">
                {report.downloads.map((download) => (
                  <button
                    type="button"
                    key={download}
                    className={`download-link ${
                      report.status === "Expired" ? "disabled" : ""
                    }`}
                    disabled={report.status === "Expired"}
                  >
                    {download}
                  </button>
                ))}
              </div>
            </div>
          ))}
        </div>

        <div className="table-footer">
          <span>Showing 1 to 4 of 28 reports</span>
          <div className="pagination">
            <button type="button" className="ghost-button">
              Previous
            </button>
            <button type="button" className="ghost-button">
              Next
            </button>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Reports;
