import { useEffect, useMemo, useState } from "react";
import {
  AlertCircleIcon,
  DownloadIcon,
  FileTextIcon,
  ReportIcon,
  SortIcon,
  SuppliersIcon,
  SwapIcon,
} from "../../components/icons/Icons";
import { reportCards } from "../../data/reports";
import {
  fetchInventory,
  formatShortDateTime,
  parseListResponse,
} from "../../utils/inventoryApi";
import "./Reports.css";

const cardIconMap = {
  summary: FileTextIcon,
  lowStock: AlertCircleIcon,
  movement: SwapIcon,
  valuation: ReportIcon,
  supplier: SuppliersIcon,
};

const getStatusClass = (status) =>
  `status-pill ${String(status || "").toLowerCase().replace(/\s+/g, "-")}`;

const Reports = () => {
  const cards = useMemo(() => reportCards, []);
  const [reports, setReports] = useState([]);
  const [meta, setMeta] = useState({
    page: 1,
    limit: 4,
    total: 0,
    totalPages: 0,
  });
  const [error, setError] = useState("");

  useEffect(() => {
    let isMounted = true;

    const loadReports = async () => {
      try {
        const payload = await fetchInventory(
          `/api/inventory/reports?limit=${meta.limit}`,
        );
        const parsed = parseListResponse(payload);
        const normalized = parsed.data.map((report, index) => ({
          id: report._id || report.id || `${index}`,
          name: report.name || "",
          created: formatShortDateTime(
            report.createdAtOverride || report.createdAt || report.created,
          ),
          generatedBy: report.generatedBy || "",
          status: report.status || "Ready",
          downloads: Array.isArray(report.downloads)
            ? report.downloads
            : ["PDF", "CSV", "EXCEL"],
        }));

        if (!isMounted) return;
        setReports(normalized);
        setMeta({
          page: parsed.page,
          limit: parsed.limit || meta.limit,
          total: parsed.total,
          totalPages: parsed.totalPages,
        });
        setError("");
      } catch (err) {
        if (!isMounted) return;
        setReports([]);
        setMeta((prev) => ({ ...prev, total: 0, totalPages: 0 }));
        setError(err?.message || "Unable to load reports.");
      }
    };

    loadReports();
    return () => {
      isMounted = false;
    };
  }, [meta.limit]);

  const total = meta.total || reports.length;
  const startIndex = total ? (meta.page - 1) * meta.limit + 1 : 0;
  const endIndex = total ? Math.min(startIndex + reports.length - 1, total) : 0;

  return (
    <section className="reports-page">
      <header className="reports-header">
        <div>
          <div className="breadcrumb">System / Reports</div>
          <h2>Analytics &amp; Reports</h2>
        </div>
        <button type="button" className="primary-button">
          <DownloadIcon className="button-icon" />
          Export All Data
        </button>
      </header>

      <div className="reports-cards">
        {cards.map((card) => {
          const Icon = cardIconMap[card.icon];
          return (
            <article className="report-card" key={card.id}>
              <div className={`report-icon ${card.tone}`}>
                {Icon ? <Icon /> : null}
              </div>
              <h3>{card.title}</h3>
              <p>{card.description}</p>
              <div className="report-actions">
                <button type="button" className="ghost-button">
                  Generate
                </button>
                <button type="button" className="ghost-button">
                  Export
                </button>
              </div>
            </article>
          );
        })}
      </div>

      <div className="reports-table-card mobile-card-table">
        <div className="reports-table-header">
          <h3>Recent Reports</h3>
          <div className="reports-table-actions">
            <button type="button" className="icon-button" aria-label="Filter">
              <SortIcon />
            </button>
            <button type="button" className="icon-button" aria-label="Refresh">
              <SwapIcon />
            </button>
          </div>
        </div>

        <div className="table-header">
          <span>Report Name</span>
          <span>Date Created</span>
          <span>Generated By</span>
          <span>Status</span>
          <span>Downloads</span>
        </div>
        <div className="table-body">
          {reports.map((report) => (
            <div className="table-row" key={report.id}>
              <div className="cell report-name full" data-label="Report Name">
                <span className="file-icon">
                  <FileTextIcon />
                </span>
                <strong>{report.name}</strong>
              </div>
              <div className="cell muted" data-label="Date Created">
                {report.created}
              </div>
              <div className="cell muted" data-label="Generated By">
                {report.generatedBy}
              </div>
              <div className="cell" data-label="Status">
                <span className={getStatusClass(report.status)}>
                  {report.status}
                </span>
              </div>
              <div className="cell downloads-cell" data-label="Downloads">
                {report.downloads.map((download) => (
                  <button
                    type="button"
                    key={download}
                    className={`download-link ${
                      report.status === "Expired" ? "disabled" : ""
                    }`}
                    disabled={report.status === "Expired"}
                  >
                    {download}
                  </button>
                ))}
              </div>
            </div>
          ))}
        </div>

        <div className="table-footer">
          <span>
            {error
              ? error
              : `Showing ${startIndex} to ${endIndex} of ${total} reports`}
          </span>
          <div className="pagination">
            <button type="button" className="ghost-button">
              Previous
            </button>
            <button type="button" className="ghost-button">
              Next
            </button>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Reports;
